export const ROUTES = {
  home: '/',
  plans: '/plans',
  plansPreset: '/plans/preset',
  plans1Month: '/plans/1-month',
  plans3Months: '/plans/3-months',
  plans6Months: '/plans/6-months',
  plans1Year: '/plans/1-year',
  verseOfTheDay: '/verse-of-the-day',
  whyStudy: '/why-study',
  donation: '/donation',
  images: '/images',
  search: '/search',
  reading: '/reading',
  chatbot: '/chatbot',
  timeline: '/timeline',
  models3d: '/3d-models',
  model3d: (id: string) => `/3d-models/${id}`,
  privacy: '/privacy',
  quiz: '/quiz',
  memorization: '/memorization',
  login: '/login',
  forgotPassword: '/forgot-password',
} as const;
